### ISSUE TITLE
Error in SpatialDataLoader

### ISSUE THREAD

**Issue by tobyli** [shilad/wikibrain#190]
@shilad @bjhecht @aaroniidx 

Have you guys encountered any problem loading spatial data with the latest version? I encountered the following problem:

```
INFO: Spatial database tables have already been initialized
Jun 04, 2014 3:02:43 PM org.wikibrain.spatial.loader.SpatialDataLoader main
INFO: Beginning to extract geographic information from Wikidata
Exception in thread "main" java.lang.AssertionError: jdbc:hsqldb:file:/Users/toby/wikibrain/./.tmp/Geotools/Databases/HSQL/v7.9.0.1/EPSG;shutdown=true
	at org.geotools.referencing.factory.epsg.ThreadedHsqlEpsgFactory.createDataSource(ThreadedHsqlEpsgFactory.java:237)
	at org.geotools.referencing.factory.epsg.ThreadedEpsgFactory.createBackingStore0(ThreadedEpsgFactory.java:386)
	at org.geotools.referencing.factory.epsg.ThreadedEpsgFactory.createBackingStore(ThreadedEpsgFactory.java:434)
	at org.geotools.referencing.factory.DeferredAuthorityFactory.getBackingStore(DeferredAuthorityFactory.java:133)
	at org.geotools.referencing.factory.BufferedAuthorityFactory.isAvailable(BufferedAuthorityFactory.java:235)
	at org.geotools.referencing.factory.DeferredAuthorityFactory.isAvailable(DeferredAuthorityFactory.java:119)
	at org.geotools.factory.FactoryRegistry.isAvailable(FactoryRegistry.java:667)
	at org.geotools.factory.FactoryRegistry.isAcceptable(FactoryRegistry.java:501)
	at org.geotools.factory.FactoryRegistry$1.filter(FactoryRegistry.java:192)
	at javax.imageio.spi.FilterIterator.advance(ServiceRegistry.java:810)
	at javax.imageio.spi.FilterIterator.<init>(ServiceRegistry.java:804)
	at javax.imageio.spi.ServiceRegistry.getServiceProviders(ServiceRegistry.java:508)
	at org.geotools.factory.FactoryRegistry.getServiceProviders(FactoryRegistry.java:197)
	at org.geotools.referencing.ReferencingFactoryFinder.getFactories(ReferencingFactoryFinder.java:180)
	at org.geotools.referencing.ReferencingFactoryFinder.getCRSAuthorityFactories(ReferencingFactoryFinder.java:455)
	at org.geotools.referencing.DefaultAuthorityFactory.getBackingFactory(DefaultAuthorityFactory.java:88)
	at org.geotools.referencing.DefaultAuthorityFactory.<init>(DefaultAuthorityFactory.java:69)
	at org.geotools.referencing.CRS.getAuthorityFactory(CRS.java:257)
	at org.geotools.referencing.CRS.decode(CRS.java:514)
	at org.geotools.referencing.CRS.decode(CRS.java:442)
	at org.geotools.jdbc.SQLDialect.createCRS(SQLDialect.java:614)
	at org.geotools.jdbc.JDBCFeatureSource.buildFeatureType(JDBCFeatureSource.java:309)
	at org.geotools.jdbc.JDBCDataStore.createFeatureSource(JDBCDataStore.java:862)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:387)
	at org.geotools.data.store.ContentDataStore.getFeatureSource(ContentDataStore.java:352)
	at org.geotools.data.store.ContentDataStore.getSchema(ContentDataStore.java:336)
	at org.wikibrain.spatial.core.dao.postgis.PostGISDB.getSchema(PostGISDB.java:399)
	at org.wikibrain.spatial.core.dao.postgis.PostGISSpatialDataDao.beginSaveGeometries(PostGISSpatialDataDao.java:231)
	at org.wikibrain.spatial.loader.SpatialDataLoader.loadWikidataData(SpatialDataLoader.java:204)
	at org.wikibrain.spatial.loader.SpatialDataLoader.main(SpatialDataLoader.java:367)
```

Tried running single-thread, cleaning m2 and lib, rebuilding database in psql. Doesn't work.

Will be trying to revert to an earlier version to see if it works.

**Comment by shilad** [comment]
Closing because it's stale.
