### ISSUE TITLE
java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()

### ISSUE THREAD

**Issue by cheetah90** [shilad/wikibrain#247]
Hi, when using WikiBrain Configuration GUI to import simple English edition with default setting, I got the following error,
```
Exception in thread "main" java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at org.wikibrain.core.dao.sql.MetaInfoSqlDao.sync(MetaInfoSqlDao.java:171)
	at org.wikibrain.core.dao.sql.MetaInfoSqlDao.getAllCummulativeInfo(MetaInfoSqlDao.java:326)
	at org.wikibrain.loader.pipeline.PipelineLoader.<init>(PipelineLoader.java:46)
	at org.wikibrain.Loader.<init>(Loader.java:72)
	at org.wikibrain.Loader.main(Loader.java:107)


LOADING FAILED!
``` 

Looks like this is a common problem when compiled with JDK 8 targeting Java 6 or 7 https://bugzilla.redhat.com/show_bug.cgi?id=1160683#c6

**Comment by shilad** [comment]
Thank you! This looks like a bug related to Java versions. I think the code
runs under Java8 but not Java7. However, I'm quite certain with a small
change we can support Java7. I'll try to stage a release to fix the problem
in the next few days.

**Comment by cheetah90** [comment]
Thanks!

**Comment by shilad** [comment]
I compiled 0.7.4 with Java7. Would you please give it a try?

**Comment by cheetah90** [comment]
I'll do later. For now, I am using Java8.
