### ISSUE TITLE
 No class found for short name RawPage

### ISSUE THREAD

**Issue by firasalmanna** [shilad/wikibrain#272]
Hello, 

I am having this problem while doing the first-time configuration using the GUI tool.
I am keeping the default params except for the language. I am using `ar` language. the download finished successfully, and the processing finished with some exception in the log. ar the end I am getting this exception:

```
running:
org.wikibrain.Loader org.wikibrain.Loader -l ar -s fetchlinks -s download -s dumploader -s redirects -s wikitext -s lucene -s phrases -s sr -c customized.conf


14:49:03.357 [main] INFO  org.wikibrain.core.cmd.Env - Configured default logging at the Info Level
14:49:03.358 [main] INFO  org.wikibrain.core.cmd.Env - To customize log4j2 set the 'log4j.configurationFile' system property or set EnvBuilder.setReconfigureLogging to false.
14:49:07.384 [main] INFO  org.wikibrain.conf.Configurator - configurator installed 75 providers for 38 classes
14:49:07.385 [main] INFO  org.wikibrain.core.cmd.Env - using override configuration files [customized.conf]
14:49:07.385 [main] INFO  org.wikibrain.core.cmd.Env - using baseDir C:\Users\firas\workspace\Text Sum\Document Clustering\wikibrain\.
14:49:07.385 [main] INFO  org.wikibrain.core.cmd.Env - using max vm heapsize of 4551MB
14:49:07.387 [main] INFO  org.wikibrain.core.cmd.Env - using languages (AR)
14:49:07.388 [main] INFO  org.wikibrain.core.cmd.Env - using maxThreads 8
14:49:07.388 [main] INFO  org.wikibrain.core.cmd.Env - using tmpDir .\.tmp
14:49:07.573 [main] WARN  org.wikibrain.core.dao.sql.WpDataSource - Raised connections per partition to 4
14:49:09.647 [main] INFO  org.wikibrain.utils.JvmUtils - found 0 classes when constructing short to full class name mapping
Exception in thread "main" org.wikibrain.core.dao.DaoException: No class found for short name RawPage
	at org.wikibrain.core.dao.sql.MetaInfoSqlDao.getAllCummulativeInfo(MetaInfoSqlDao.java:344)
	at org.wikibrain.loader.pipeline.PipelineLoader.<init>(PipelineLoader.java:46)
	at org.wikibrain.Loader.<init>(Loader.java:81)
	at org.wikibrain.Loader.main(Loader.java:121)


LOADING FAILED!
```

I tried to restart the process, but I am getting the same error. Any ideas?

**Comment by MatteoRebecchiMari** [comment]
I've spent half day to resolve the problem. 
For me the trick is to `delete the "db"` folder and restart the procedure.

**Comment by MatteoRebecchiMari** [comment]
Today i have found the issues. 

The class **org.wikibrain.utils.JvmUtils** when is try to find the class have a limitation for the *.jar file SIZE ( 8 Megabytes),  so the jar containing the **RawPage** class (wikibrain.withdeps-X.X.X.jar) is skipped and the class is not found. 

To jump the problem you must add to the classpath the wikibrain-core-X.X.X.jar file.

To obtain the `wikibrain-core-0.9.1.jar` file you need to rebuild the maven project.
After you have build the jar you add it into the wikibrain dictionary folder.

An example for version 0.9.1 -> Load the GUI manually adding the core.jar to the classpath.
In the folder of wikibrain dictionary call

`java -cp wikibrain-withdeps-0.9.1.jar:wikibrain-core-0.9.1.jar -Xmx8000M org.wikibrain.GuiLoader`


This solve the issues for RawPage not found.
